name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          # Aquí le decimos que busque el archivo gradle dentro de tu carpeta
          cache-dependency-path: RutaCom-app/*.gradle*

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: RutaCom-app

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: RutaCom-app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RutaCom-debug-apk
          path: RutaCom-app/app/build/outputs/apk/debug/*.apk
          
